name: test
on: [push, pull_request]

jobs:
  test:
    name: "Test on Node.js 16"
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
